CREATE TABLE grapes (
  name TEXT PRIMARY KEY NOT NULL
);

INSERT INTO grapes ('name') VALUES 
('Aglianico'),
('Albariño'),
('Barbera'),
('Cabernet franc'),
('Cabernet sauvignon'),
('Carignan'),
('Carmenère'),
('Chardonnay'),
('Chenin blanc'),
('Corvina'),
('Cinsault'),
('Dolcetto'),
('Furmint'),
('Gamay'),
('Garganega'),
('Gewürztraminer'),
('Godello'),
('Grenache'),
('Grenache blanc'),
('Grüner veltliner'),
('Malbec'),
('Marsanne'),
('Melon de bourgogne/muscadet'),
('Merlot'),
('Mourvèdre'),
('Muskat'),
('Nebbiolo'),
('Nerello mascalese'),
('Pinot blanc'),
('Pinot gris'),
('Pinot noir'),
('Pinotage'),
('Primitivo'),
('Riesling'),
('Sangiovese'),
('Sauvignon blanc'),
('Savagnin'),
('Semillon'),
('Solaris'),
('Syrah/shiraz'),
('Tannat'),
('Tempranillo'),
('Torrontés'),
('Touriga nacional'),
('Verdicchio'),
('Vermentino'),
('Viognier'),
('Zinfandel');
